# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.159.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317

  prometheus:
    image: prom/prometheus:v3.14.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  tempo:
    image: grafana/tempo:3.0.3
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - 3200:3200

  loki:
    image: grafana/loki:3.7.7
    command: ["-config.file=/etc/loki-config.yaml"]
    volumes:
      - ./loki-config.yaml:/etc/loki-config.yaml
    ports:
      - 3100:3100

  grafana:
    image: grafana/grafana:13.2.0
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - tempo
      - loki

  postgres:
    image: docker.io/postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: exam-password
      POSTGRES_USER: exam-user
      POSTGRES_DB: exam-db
    ports:
      - "5432:5432"
