openapi: "3.0.0"
info:
  version: 1.0.0
  title: Minimal API server
servers:
  - url: "{scheme}://{host}/"
    variables:
      scheme:
        default: http
      host:
        default: localhost:8080
paths:
  #############################################################################
  # Author
  /author:
    get:
      summary: Get all authors
      operationId: GetAllAuthors
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
    post:
      summary: create author
      operationId: CreateAuthor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthorCreateRequest"
      responses:
        "201":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Author"
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
  /author/{id}:
    get:
      summary: Get author
      operationId: GetAuthor
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Author"
        "404":
          description: not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
    put:
      summary: update author
      operationId: UpdateAuthor
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthorCreateRequest"
      responses:
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
        "404":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"

  #############################################################################
  # Book
  /book:
    post:
      summary: create book
      operationId: CreateBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBookRequest"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        "400":
          description: not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ErrorMsg"
  /book/{id}:
    get:
      summary: get book
      operationId: GetBook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        "404":
          description: not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
  /book/{bookId}/publish:
    post:
      summary: publish book
      operationId: PublishBook
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: authorId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: ok
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
        "404":
          description: not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMsg"

components:
  schemas:
    # base types
    Author:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        bio:
          type: string
    ErrorMsg:
      type: object
      required:
        - msg
        - requestId
      properties:
        msg:
          type: string
        requestId:
          type: string
          format: uuid
    AuthorCreateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        bio:
          type: string
    Book:
      type: object
      required:
        - id
        - title
        - publishedAt
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        publishedAt:
          type: string
          format: date-time
    CreateBookRequest:
      type: object
      required:
        - title
        - publishedAt
      properties:
        title:
          type: string
        publishedAt:
          type: string
          format: date-time
