// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: book.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
insert into books (title, published_at)
values($1, $2)
returning id, title, published_at
`

type CreateBookParams struct {
	Title       string             `json:"title"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook, arg.Title, arg.PublishedAt)
	var i Book
	err := row.Scan(&i.ID, &i.Title, &i.PublishedAt)
	return i, err
}

const getBook = `-- name: GetBook :one
select id, title, published_at from books where id = $1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(&i.ID, &i.Title, &i.PublishedAt)
	return i, err
}

const publishBook = `-- name: PublishBook :exec
insert into book_author (book_id, author_id)
values ($1, $2)
`

type PublishBookParams struct {
	BookID   int64 `json:"book_id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) PublishBook(ctx context.Context, arg PublishBookParams) error {
	_, err := q.db.Exec(ctx, publishBook, arg.BookID, arg.AuthorID)
	return err
}
