// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64   `json:"id"`
	Name string  `json:"name"`
	Bio  *string `json:"bio"`
}

type Book struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type BookAuthor struct {
	BookID   int64 `json:"book_id"`
	AuthorID int64 `json:"author_id"`
}
